name: CreateNotebook

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        
      - name: Check out repository 
        run: echo "The name of current branch is ${{ github.ref }} and its repository is ${{ github.repository }}."

      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'

      - name: Create Notebook
        shell: bash
        run: |
          julia --project=.
          julia 'using Pkg'
          julia 'Pkg.activate(@__DIR__)'
          julia 'Pkg.instantiate()'
          julia 'using SIIPExamples'
          julia 'using Literate'
          julia 'SIIPExamples.literate_all()'          


      - name: Commit Files to 
        run: |
          git config --global user.name "ptn111"
          git config --global user.email "32492807+ptn111@users.noreply.github.com"

          git add -A
          git commit -a -m "Push *.ipynb to notebook branch"
          git branch notebook
          git push --force origin master:notebook

