name: CreateNotebook

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        
      - name: Check out repository 
        run: echo "The name of current branch is ${{ github.ref }} and its repository is ${{ github.repository }}."

      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
       
      - name: Create a gen_notebook.jl
        run: |
          echo "import Pkg"                    > gen_notebook.jl
          echo "Pkg.activate(@__DIR__)"       >> gen_notebook.jl
          echo "Pkg.instantiate()"            >> gen_notebook.jl
          echo "using SIIPExamples"           >> gen_notebook.jl
          echo "using Literate"               >> gen_notebook.jl
          echo "SIIPExamples.literate_all()"  >> gen_notebook.jl

      - name: Call Julia to create Notebook
        shell: bash
        run: |
          julia --project=.
          julia 'gen_notebook.jl'   


      - name: Commit Files to 
        run: |
          git config --global user.name "ptn111"
          git config --global user.email "32492807+ptn111@users.noreply.github.com"

          git add -A
          git commit -a -m "Push *.ipynb to notebook branch"
          git branch notebook
          git push --force origin master:notebook

